# .pre-commit-config.yaml
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.10
    hooks:
      - id: ruff              # lint
        args: [--fix]
      - id: ruff-format       # format

 # Mypy - static type checking
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: uv run mypy src
        language: system
        types: [python]
        pass_filenames: false  # let mypy use your pyproject.toml config

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: uv run pytest --cov --cov-report=term-missing
        language: system
        pass_filenames: false
        always_run: true